<a href="https://colab.research.google.com/github/Lrnzjsph/eljay_is_available_/blob/main/Countriescsv(Group1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
import numpy as np

In [101]:
# Import the 'countries.csv' as df_countries.
df_countries = pd.read_csv('/content/sample_data/Countries.csv')
df_countries

,Country Name,Country Code,Year,Agriculture (% GDP),Ease of Doing Business,Education Expenditure (% GDP),Export (% GDP),GDP,Health Expenditure (% GDP),Import (% GDP),...,Population,Land,Continent Name,Export,Import,Education Expenditure,Health Expenditure,Net Trade,GDP Per Capita,Population Density
0,Afghanistan,AFG,2000,27.501127,40.717968,13.670101,NaN,1.415197e+10,10.902580,NaN,...,19542982,652860.0,Asia,NaN,NaN,1.934589e+09,1.542930e+09,NaN,724.145910,29.934415
1,Afghanistan,AFG,2001,27.501127,40.717968,13.670101,NaN,1.415197e+10,10.902580,NaN,...,19688632,652860.0,Asia,NaN,NaN,1.934589e+09,1.542930e+09,NaN,718.788917,30.157510
2,Afghanistan,AFG,2002,38.627892,40.717968,13.670101,NaN,3.854235e+09,9.443391,NaN,...,21000256,652860.0,Asia,NaN,NaN,5.268779e+08,3.639705e+08,NaN,183.532775,32.166553
3,Afghanistan,AFG,2003,37.418855,40.717968,13.670101,NaN,4.539497e+09,8.941258,NaN,...,22645130,652860.0,Asia,NaN,NaN,6.205538e+08,4.058881e+08,NaN,200.462376,34.686043
4,Afghanistan,AFG,2004,29.721067,40.717968,13.670101,NaN,5.220825e+09,9.808474,NaN,...,23553551,652860.0,Asia,NaN,NaN,7.136921e+08,5.120832e+08,NaN,221.657662,36.077491
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5101,Zimbabwe,ZWE,2018,7.319375,50.509980,19.039841,26.163973,3.415607e+10,4.670418,28.386297,...,15052184,390760.0,Africa,8.936585e+09,9.695644e+09,6.503261e+09,1.595231e+09,-7.590586e+08,2269.177012,38.520278
5102,Zimbabwe,ZWE,2019,9.819262,54.469350,22.837985,27.163459,2.183223e+10,3.659765,25.524111,...,15354608,390760.0,Africa,5.930390e+09,5.572484e+09,4.986042e+09,7.990086e+08,3.579063e+08,1421.868596,39.294216
5103,Zimbabwe,ZWE,2020,8.772859,49.833418,15.666611,25.917014,2.150970e+10,3.425581,28.733547,...,15669666,390760.0,Africa,5.574672e+09,6.180499e+09,3.369841e+09,7.368322e+08,-6.058277e+08,1372.696674,40.100486
5104,Zimbabwe,ZWE,2021,8.849899,49.833418,22.837985,25.411446,2.837124e+10,6.704907,30.901234,...,15993524,390760.0,Africa,7.209542e+09,8.767063e+09,6.479419e+09,1.902265e+09,-1.557521e+09,1773.920411,40.929276
5105,Zimbabwe,ZWE,2022,12.069543,49.833418,22.837985,28.908919,2.067806e+10,6.704907,39.540243,...,16320537,390760.0,Africa,5.977802e+09,8.176153e+09,4.722451e+09,1.386444e+09,-2.198351e+09,1266.996031,41.766140

In [43]:
# Use as appropriate method to check if the above data set is truly a dataframe.

type(df_countries)

pandas.core.frame.DataFrame

In [44]:
#Print the column names using the '.column' attributes.

list(df_countries.columns)[0:25]

['Country Name',
 'Country Code',
 'Year',
 'Agriculture (% GDP)',
 'Ease of Doing Business',
 'Education Expenditure (% GDP)',
 'Export (% GDP)',
 'GDP',
 'Health Expenditure (% GDP)',
 'Import (% GDP)',
 'Industry (% GDP)',
 'Inflation Rate',
 'R&D',
 'Service (% GDP)',
 'Unemployment',
 'Population',
 'Land',
 'Continent Name',
 'Export',
 'Import',
 'Education Expenditure',
 'Health Expenditure',
 'Net Trade',
 'GDP Per Capita',
 'Population Density']

In [12]:
# What is the shape of the dataset

df_countries.shape

(5106, 25)

In [104]:
# Store the number of rows in a variable called 'nrow' using the result above.

nrow = df_countries.shape
nrow[0]

5106

In [46]:
'''
Rename the columns: Agriculture (% GDP), Education Expenditure (% GDP), Export (% GDP), Education Expenditure (% GDP), Export (% GDP),
Health Expenditure (% GDP), Industry (% GDP), Service (% GDP)  to: agriculture, education_expenditure, export, education_expenditure,
export, health_expenditure, industry, service  respectively.
'''
df_countries = df_countries.rename(columns={"Agriculture_(%GDP)": "Agriculture", "Education_Expenditure_(%GDP)": "Education_Expenditure", "Education_Expenditure_(%GDP)": "Education_Expenditure","Export_(%GDP)": "Export", "Health_Expenditure_(%GDP)": "Health_Expenditure", "Industry_(%GDP)": "Industry", "Service_(%GDP)": "Service"})
print(df_countries)

     Country Name Country Code  Year  Agriculture (% GDP)  \
0     Afghanistan          AFG  2000            27.501127
1     Afghanistan          AFG  2001            27.501127
2     Afghanistan          AFG  2002            38.627892
3     Afghanistan          AFG  2003            37.418855
4     Afghanistan          AFG  2004            29.721067
...           ...          ...   ...                  ...
5101     Zimbabwe          ZWE  2018             7.319375
5102     Zimbabwe          ZWE  2019             9.819262
5103     Zimbabwe          ZWE  2020             8.772859
5104     Zimbabwe          ZWE  2021             8.849899
5105     Zimbabwe          ZWE  2022            12.069543

      Ease of Doing Business  Education Expenditure (% GDP)  Export (% GDP)  \
0                  40.717968                      13.670101             NaN
1                  40.717968                      13.670101             NaN
2                  40.717968                      13.670101             NaN
3                  40.717968                      13.670101             NaN
4                  40.717968                      13.670101             NaN
...                      ...                            ...             ...
5101               50.509980                      19.039841       26.163973
5102               54.469350                      22.837985       27.163459
5103               49.833418                      15.666611       25.917014
5104               49.833418                      22.837985       25.411446
5105               49.833418                      22.837985       28.908919

               GDP  Health Expenditure (% GDP)  Import (% GDP)  ...  \
0     1.415197e+10                   10.902580             NaN  ...
1     1.415197e+10                   10.902580             NaN  ...
2     3.854235e+09                    9.443391             NaN  ...
3     4.539497e+09                    8.941258             NaN  ...
4     5.220825e+09                    9.808474             NaN  ...
...            ...                         ...             ...  ...
5101  3.415607e+10                    4.670418       28.386297  ...
5102  2.183223e+10                    3.659765       25.524111  ...
5103  2.150970e+10                    3.425581       28.733547  ...
5104  2.837124e+10                    6.704907       30.901234  ...
5105  2.067806e+10                    6.704907       39.540243  ...

      Population      Land  Continent Name        Export        Import  \
0       19542982  652860.0            Asia           NaN           NaN
1       19688632  652860.0            Asia           NaN           NaN
2       21000256  652860.0            Asia           NaN           NaN
3       22645130  652860.0            Asia           NaN           NaN
4       23553551  652860.0            Asia           NaN           NaN
...          ...       ...             ...           ...           ...
5101    15052184  390760.0          Africa  8.936585e+09  9.695644e+09
5102    15354608  390760.0          Africa  5.930390e+09  5.572484e+09
5103    15669666  390760.0          Africa  5.574672e+09  6.180499e+09
5104    15993524  390760.0          Africa  7.209542e+09  8.767063e+09
5105    16320537  390760.0          Africa  5.977802e+09  8.176153e+09

      Education Expenditure  Health Expenditure     Net Trade  GDP Per Capita  \
0              1.934589e+09        1.542930e+09           NaN      724.145910
1              1.934589e+09        1.542930e+09           NaN      718.788917
2              5.268779e+08        3.639705e+08           NaN      183.532775
3              6.205538e+08        4.058881e+08           NaN      200.462376
4              7.136921e+08        5.120832e+08           NaN      221.657662
...                     ...                 ...           ...             ...
5101           6.503261e+09        1.595231e+09 -7.590586e+08     2269.177012
5102           4.986042e+09        7.990086e+08  3.579063e+08     1421.868596
5103           3.369841e+09        7.368322e+08 -6.058277e+08     1372.696674
5104           6.479419e+09        1.902265e+09 -1.557521e+09     1773.920411
5105           4.722451e+09        1.386444e+09 -2.198351e+09     1266.996031

      Population Density
0              29.934415
1              30.157510
2              32.166553
3              34.686043
4              36.077491
...                  ...
5101           38.520278
5102           39.294216
5103           40.100486
5104           40.929276
5105           41.766140

[5106 rows x 25 columns]

In [20]:
'''
Investigate the data type of each column and determine whether the assigned data types are appropriate and consistent.
Where necessary, convert columns to the correct data types.
'''
df_countries.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5106 entries, 0 to 5105
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Country Name                   5106 non-null   object
 1   Country Code                   5106 non-null   object
 2   Year                           5106 non-null   int64
 3   Agriculture (% GDP)            4830 non-null   float64
 4   Ease of Doing Business         4508 non-null   float64
 5   Education Expenditure (% GDP)  4738 non-null   float64
 6   Export (% GDP)                 4646 non-null   float64
 7   GDP                            5037 non-null   float64
 8   Health Expenditure (% GDP)     4531 non-null   float64
 9   Import (% GDP)                 4646 non-null   float64
 10  Industry (% GDP)               4853 non-null   float64
 11  Inflation Rate                 4554 non-null   float64
 12  R&D                            3588 non-null   float64
 13  Service (% GDP)                4807 non-null   float64
 14  Unemployment                   4439 non-null   float64
 15  Population                     5106 non-null   int64
 16  Land                           5106 non-null   float64
 17  Continent Name                 5106 non-null   object
 18  Export                         4646 non-null   float64
 19  Import                         4646 non-null   float64
 20  Education Expenditure          4692 non-null   float64
 21  Health Expenditure             4531 non-null   float64
 22  Net Trade                      4646 non-null   float64
 23  GDP Per Capita                 5037 non-null   float64
 24  Population Density             5106 non-null   float64
dtypes: float64(20), int64(2), object(3)
memory usage: 997.4+ KB

In [47]:
df_countries.columns

Index(['Country Name', 'Country Code', 'Year', 'Agriculture (% GDP)',
       'Ease of Doing Business', 'Education Expenditure (% GDP)',
       'Export (% GDP)', 'GDP', 'Health Expenditure (% GDP)', 'Import (% GDP)',
       'Industry (% GDP)', 'Inflation Rate', 'R&D', 'Service (% GDP)',
       'Unemployment', 'Population', 'Land', 'Continent Name', 'Export',
       'Import', 'Education Expenditure', 'Health Expenditure', 'Net Trade',
       'GDP Per Capita', 'Population Density'],
      dtype='object')

In [50]:
# Convert the year to a date type using an appropriate method.
df_countries['Year'] = pd.to_datetime(df_countries['Year'], format='%Y')
df_countries.head()

,Country Name,Country Code,Year,Agriculture (% GDP),Ease of Doing Business,Education Expenditure (% GDP),Export (% GDP),GDP,Health Expenditure (% GDP),Import (% GDP),...,Population,Land,Continent Name,Export,Import,Education Expenditure,Health Expenditure,Net Trade,GDP Per Capita,Population Density
0,Afghanistan,AFG,2000-01-01,27.501127,40.717968,13.670101,NaN,1.415197e+10,10.902580,NaN,...,19542982,652860.0,Asia,NaN,NaN,1.934589e+09,1.542930e+09,NaN,724.145910,29.934415
1,Afghanistan,AFG,2001-01-01,27.501127,40.717968,13.670101,NaN,1.415197e+10,10.902580,NaN,...,19688632,652860.0,Asia,NaN,NaN,1.934589e+09,1.542930e+09,NaN,718.788917,30.157510
2,Afghanistan,AFG,2002-01-01,38.627892,40.717968,13.670101,NaN,3.854235e+09,9.443391,NaN,...,21000256,652860.0,Asia,NaN,NaN,5.268779e+08,3.639705e+08,NaN,183.532775,32.166553
3,Afghanistan,AFG,2003-01-01,37.418855,40.717968,13.670101,NaN,4.539497e+09,8.941258,NaN,...,22645130,652860.0,Asia,NaN,NaN,6.205538e+08,4.058881e+08,NaN,200.462376,34.686043
4,Afghanistan,AFG,2004-01-01,29.721067,40.717968,13.670101,NaN,5.220825e+09,9.808474,NaN,...,23553551,652860.0,Asia,NaN,NaN,7.136921e+08,5.120832e+08,NaN,221.657662,36.077491

In [61]:
# Use appropriate method to check missing values and duplicates.
df_countries.duplicated().any()  #to check for duplicate items

np.False_

In [52]:
df_countries.isna().sum() #to check for missing values in the dataset, this also gives the total number of missing variables in the data set and the columns affected.

Country Name                        0
Country Code                        0
Year                                0
Agriculture (% GDP)               276
Ease of Doing Business            598
Education Expenditure (% GDP)     368
Export (% GDP)                    460
GDP                                69
Health Expenditure (% GDP)        575
Import (% GDP)                    460
Industry (% GDP)                  253
Inflation Rate                    552
R&D                              1518
Service (% GDP)                   299
Unemployment                      667
Population                          0
Land                                0
Continent Name                      0
Export                            460
Import                            460
Education Expenditure             414
Health Expenditure                575
Net Trade                         460
GDP Per Capita                     69
Population Density                  0
dtype: int64

In [64]:
# Delete rows with missing values and duplicates using appropriate method.
df_countries.dropna(inplace=True) #this deletes rows with missing values

In [54]:
#df_countries.drop_duplicates() #this deletes ro

In [71]:
# Save the dataset to your work directory as “cleaned_data.csv”.

# === SAVE IT AS CSV ===
df_countries.to_csv("cleaned_data.csv", index=False)

print("File saved successfully as 'cleaned_data.csv'!")

File saved successfully as 'cleaned_data.csv'!

In [55]:
# Select only the Country Name, Year, and GDP columns.
df_selected = df_countries[['Country Name', 'Year', 'GDP']]
print(df_selected)

     Country Name       Year           GDP
23        Albania 2000-01-01  3.480355e+09
24        Albania 2001-01-01  3.922101e+09
25        Albania 2002-01-01  4.348068e+09
26        Albania 2003-01-01  5.611496e+09
27        Albania 2004-01-01  7.184686e+09
...           ...        ...           ...
5078       Zambia 2018-01-01  2.631151e+10
5079       Zambia 2019-01-01  2.330867e+10
5080       Zambia 2020-01-01  1.811064e+10
5081       Zambia 2021-01-01  2.214765e+10
5082       Zambia 2022-01-01  2.978445e+10

[3174 rows x 3 columns]

In [58]:
# Create a new column GDP_in _billions by dividing GDP by 1e9.
df_countries['GDP_in_billions'] = df_countries['GDP'] / 1e9
df_countries.head(10)

,Country Name,Country Code,Year,Agriculture (% GDP),Ease of Doing Business,Education Expenditure (% GDP),Export (% GDP),GDP,Health Expenditure (% GDP),Import (% GDP),...,Continent Name,Export,Import,Education Expenditure,Health Expenditure,Net Trade,GDP Per Capita,Population Density,GDP_in_billions,High_Population
23,Albania,ALB,2000-01-01,24.515412,64.76366,10.137030,20.115286,3.480355e+09,5.944186,43.338788,...,Europe,7.000834e+08,1.508344e+09,3.528046e+08,206878780.6,-8.082604e+08,1126.683340,107.444417,3.480355,False
24,Albania,ALB,2001-01-01,22.716164,64.76366,10.581930,21.333411,3.922101e+09,5.925833,45.157613,...,Europe,8.367179e+08,1.771127e+09,4.150340e+08,232417133.3,-9.344092e+08,1281.659826,106.440800,3.922101,False
25,Albania,ALB,2002-01-01,22.025114,64.76366,9.886920,20.945616,4.348068e+09,5.664600,47.579452,...,Europe,9.107297e+08,2.068787e+09,4.298900e+08,246300669.3,-1.158057e+09,1425.124219,106.122087,4.348068,False
26,Albania,ALB,2003-01-01,21.978257,64.76366,10.573600,20.847386,5.611496e+09,6.198919,46.173175,...,Europe,1.169850e+09,2.591006e+09,5.933372e+08,347852097.6,-1.421156e+09,1846.120121,105.725774,5.611496,False
27,Albania,ALB,2004-01-01,20.537486,64.76366,10.703160,22.217561,7.184686e+09,6.055778,44.829627,...,Europe,1.596262e+09,3.220868e+09,7.689884e+08,435088656.8,-1.624606e+09,2373.581292,105.284835,7.184686,False
28,Albania,ALB,2005-01-01,18.845309,64.76366,11.357970,23.012991,8.052077e+09,5.833030,47.859356,...,Europe,1.853024e+09,3.853672e+09,9.145525e+08,469680097.0,-2.000648e+09,2673.787803,104.747374,8.052077,False
29,Albania,ALB,2006-01-01,17.708354,64.76366,10.932950,25.209608,8.896075e+09,5.685989,49.057483,...,Europe,2.242666e+09,4.364190e+09,9.726034e+08,505829836.8,-2.121525e+09,2972.743618,104.088591,8.896075,False
30,Albania,ALB,2007-01-01,17.153620,64.76366,11.177190,28.247865,1.067732e+10,5.708428,54.954215,...,Europe,3.016116e+09,5.867640e+09,1.193425e+09,609507393.1,-2.851524e+09,3595.038302,103.304939,10.677325,False
31,Albania,ALB,2008-01-01,16.837054,64.76366,11.672968,25.302418,1.288135e+10,5.509624,52.149333,...,Europe,3.259294e+09,6.717540e+09,1.503636e+09,709714171.5,-3.458246e+09,4370.539711,102.515270,12.881353,False
32,Albania,ALB,2009-01-01,16.794384,64.76366,11.672968,25.240749,1.204421e+10,5.727621,49.854166,...,Europe,3.040048e+09,6.004538e+09,1.405916e+09,689846399.5,-2.964491e+09,4114.134041,101.826748,12.044206,False

In [62]:
# Add a column called High_Population to label entries where the population is above 100 million.
df_countries['High_Population'] = df_countries['Population'] > 100000000
df_countries

,Country Name,Country Code,Year,Agriculture (% GDP),Ease of Doing Business,Education Expenditure (% GDP),Export (% GDP),GDP,Health Expenditure (% GDP),Import (% GDP),...,Continent Name,Export,Import,Education Expenditure,Health Expenditure,Net Trade,GDP Per Capita,Population Density,GDP_in_billions,High_Population
23,Albania,ALB,2000-01-01,24.515412,64.763660,10.137030,20.115286,3.480355e+09,5.944186,43.338788,...,Europe,7.000834e+08,1.508344e+09,3.528046e+08,2.068788e+08,-8.082604e+08,1126.683340,107.444417,3.480355,False
24,Albania,ALB,2001-01-01,22.716164,64.763660,10.581930,21.333411,3.922101e+09,5.925833,45.157613,...,Europe,8.367179e+08,1.771127e+09,4.150340e+08,2.324171e+08,-9.344092e+08,1281.659826,106.440800,3.922101,False
25,Albania,ALB,2002-01-01,22.025114,64.763660,9.886920,20.945616,4.348068e+09,5.664600,47.579452,...,Europe,9.107297e+08,2.068787e+09,4.298900e+08,2.463007e+08,-1.158057e+09,1425.124219,106.122087,4.348068,False
26,Albania,ALB,2003-01-01,21.978257,64.763660,10.573600,20.847386,5.611496e+09,6.198919,46.173175,...,Europe,1.169850e+09,2.591006e+09,5.933372e+08,3.478521e+08,-1.421156e+09,1846.120121,105.725774,5.611496,False
27,Albania,ALB,2004-01-01,20.537486,64.763660,10.703160,22.217561,7.184686e+09,6.055778,44.829627,...,Europe,1.596262e+09,3.220868e+09,7.689884e+08,4.350887e+08,-1.624606e+09,2373.581292,105.284835,7.184686,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5078,Zambia,ZMB,2018-01-01,3.341124,65.711700,17.118719,37.957405,2.631151e+10,5.056766,36.930965,...,Africa,9.987165e+09,9.717093e+09,4.504193e+09,1.330511e+09,2.700717e+08,1475.199836,23.698719,26.311506,False
5079,Zambia,ZMB,2019-01-01,2.860775,66.936480,15.291870,34.636193,2.330867e+10,5.319501,34.155012,...,Africa,8.073235e+09,7.961078e+09,3.564331e+09,1.239905e+09,1.121567e+08,1268.120941,24.422313,23.308668,False
5080,Zambia,ZMB,2020-01-01,2.977086,63.517218,12.378020,46.790165,1.811064e+10,5.617884,32.535322,...,Africa,8.473998e+09,5.892355e+09,2.241739e+09,1.017435e+09,2.581643e+09,956.831748,25.149433,18.110639,False
5081,Zambia,ZMB,2021-01-01,3.393277,63.517218,11.514140,52.078387,2.214765e+10,5.200252,33.913790,...,Africa,1.153414e+10,7.511107e+09,2.550111e+09,1.151733e+09,4.023031e+09,1137.344395,25.874125,22.147650,False
5082,Zambia,ZMB,2022-01-01,3.388658,63.517218,10.447814,38.431953,2.978445e+10,5.200252,27.156932,...,Africa,1.144675e+10,8.088544e+09,3.111824e+09,1.548867e+09,3.358203e+09,1487.907764,26.597673,29.784454,False

In [68]:
# Create a new column named category that classifies countries based on GDP per capita as follows:
'''Low: GDP per capita < 1,000
Medium: 1,000 ≤ GDP per capita < 10,000
High: GDP per capita ≥ 10,000'''
df_countries['Category'] = pd.cut(df_countries['GDP Per Capita'], bins=[0, 1000, 10000, np.inf], labels=['Low', 'Medium', 'High'])
df_countries.head(10)

,Country Name,Country Code,Year,Agriculture (% GDP),Ease of Doing Business,Education Expenditure (% GDP),Export (% GDP),GDP,Health Expenditure (% GDP),Import (% GDP),...,Export,Import,Education Expenditure,Health Expenditure,Net Trade,GDP Per Capita,Population Density,GDP_in_billions,High_Population,Category
23,Albania,ALB,2000-01-01,24.515412,64.76366,10.137030,20.115286,3.480355e+09,5.944186,43.338788,...,7.000834e+08,1.508344e+09,3.528046e+08,206878780.6,-8.082604e+08,1126.683340,107.444417,3.480355,False,Medium
24,Albania,ALB,2001-01-01,22.716164,64.76366,10.581930,21.333411,3.922101e+09,5.925833,45.157613,...,8.367179e+08,1.771127e+09,4.150340e+08,232417133.3,-9.344092e+08,1281.659826,106.440800,3.922101,False,Medium
25,Albania,ALB,2002-01-01,22.025114,64.76366,9.886920,20.945616,4.348068e+09,5.664600,47.579452,...,9.107297e+08,2.068787e+09,4.298900e+08,246300669.3,-1.158057e+09,1425.124219,106.122087,4.348068,False,Medium
26,Albania,ALB,2003-01-01,21.978257,64.76366,10.573600,20.847386,5.611496e+09,6.198919,46.173175,...,1.169850e+09,2.591006e+09,5.933372e+08,347852097.6,-1.421156e+09,1846.120121,105.725774,5.611496,False,Medium
27,Albania,ALB,2004-01-01,20.537486,64.76366,10.703160,22.217561,7.184686e+09,6.055778,44.829627,...,1.596262e+09,3.220868e+09,7.689884e+08,435088656.8,-1.624606e+09,2373.581292,105.284835,7.184686,False,Medium
28,Albania,ALB,2005-01-01,18.845309,64.76366,11.357970,23.012991,8.052077e+09,5.833030,47.859356,...,1.853024e+09,3.853672e+09,9.145525e+08,469680097.0,-2.000648e+09,2673.787803,104.747374,8.052077,False,Medium
29,Albania,ALB,2006-01-01,17.708354,64.76366,10.932950,25.209608,8.896075e+09,5.685989,49.057483,...,2.242666e+09,4.364190e+09,9.726034e+08,505829836.8,-2.121525e+09,2972.743618,104.088591,8.896075,False,Medium
30,Albania,ALB,2007-01-01,17.153620,64.76366,11.177190,28.247865,1.067732e+10,5.708428,54.954215,...,3.016116e+09,5.867640e+09,1.193425e+09,609507393.1,-2.851524e+09,3595.038302,103.304939,10.677325,False,Medium
31,Albania,ALB,2008-01-01,16.837054,64.76366,11.672968,25.302418,1.288135e+10,5.509624,52.149333,...,3.259294e+09,6.717540e+09,1.503636e+09,709714171.5,-3.458246e+09,4370.539711,102.515270,12.881353,False,Medium
32,Albania,ALB,2009-01-01,16.794384,64.76366,11.672968,25.240749,1.204421e+10,5.727621,49.854166,...,3.040048e+09,6.004538e+09,1.405916e+09,689846399.5,-2.964491e+09,4114.134041,101.826748,12.044206,False,Medium

In [69]:
# Sort the dataset by GDP in descending order to find the highest GDP countries.
df_countries.sort_values(by='GDP Per Capita', ascending=False) #the out put of this code rearranges the indexes of the dataset so we use the reset index function to re-number the data accordingly#

,Country Name,Country Code,Year,Agriculture (% GDP),Ease of Doing Business,Education Expenditure (% GDP),Export (% GDP),GDP,Health Expenditure (% GDP),Import (% GDP),...,Export,Import,Education Expenditure,Health Expenditure,Net Trade,GDP Per Capita,Population Density,GDP_in_billions,High_Population,Category
2758,Luxembourg,LUX,2021-01-01,0.195018,69.421058,9.613329,211.433432,8.550624e+10,5.354177,176.687001,...,1.810000e+11,1.510000e+11,8.219996e+09,4.578155e+09,2.971037e+10,133590.147000,247.128958,85.506244,False,High
2759,Luxembourg,LUX,2022-01-01,0.245201,69.421058,9.613329,209.366433,8.227481e+10,5.995117,175.111415,...,1.720000e+11,1.440000e+11,7.909348e+09,4.932471e+09,2.818325e+10,126426.089900,251.264093,82.274812,False,High
2751,Luxembourg,LUX,2014-01-01,0.289550,69.421058,9.493740,182.782592,6.880481e+10,5.230409,150.646261,...,1.260000e+11,1.040000e+11,6.532150e+09,3.598773e+09,2.211134e+10,123678.702100,214.794981,68.804812,False,High
2745,Luxembourg,LUX,2008-01-01,0.307779,69.421058,9.613329,161.494762,5.884428e+10,6.231011,130.718719,...,9.503043e+10,7.692049e+10,5.656894e+09,3.666593e+09,1.810994e+10,120422.137900,188.667954,58.844278,False,High
2750,Luxembourg,LUX,2013-01-01,0.261907,69.421058,9.015843,176.383331,6.520328e+10,5.235574,144.150175,...,1.150000e+11,9.399064e+10,5.878625e+09,3.413766e+09,2.101707e+10,120000.140700,209.791506,65.203276,False,High
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1518,Ethiopia,ETH,2000-01-01,44.666018,45.805204,14.907730,9.891768,8.242350e+09,4.365047,24.807325,...,8.153141e+08,2.044707e+09,1.228747e+09,3.597824e+08,-1.229392e+09,122.961665,60.700776,8.242350,False,Low
1519,Ethiopia,ETH,2001-01-01,42.340571,45.805204,14.461770,9.891768,8.231326e+09,4.723167,24.807325,...,8.142236e+08,2.041972e+09,1.190395e+09,3.887793e+08,-1.227748e+09,119.261857,62.500165,8.231326,False,Low
1521,Ethiopia,ETH,2003-01-01,37.285055,45.805204,23.833811,9.891768,8.623691e+09,4.899709,24.807325,...,8.530355e+08,2.139307e+09,2.055354e+09,4.225358e+08,-1.286272e+09,117.860165,66.258116,8.623691,False,Low
762,Burundi,BDI,2003-01-01,42.841284,46.083270,17.169737,6.381414,7.846544e+08,6.313277,20.994898,...,5.007205e+07,1.647374e+08,1.347231e+08,4.953741e+07,-1.146653e+08,114.367007,246.526985,0.784654,False,Low
1520,Ethiopia,ETH,2002-01-01,38.692372,45.805204,16.187750,9.891768,7.850809e+09,4.712630,24.807325,...,7.765838e+08,1.947576e+09,1.270869e+09,3.699796e+08,-1.170992e+09,110.460875,64.360423,7.850809,False,Low

In [74]:
#. Arrange countries within the same continent in ascending order of Population Density.
df_countries.sort_values(by='Population Density', ascending=True)

,Country Name,Country Code,Year,Agriculture (% GDP),Ease of Doing Business,Education Expenditure (% GDP),Export (% GDP),GDP,Health Expenditure (% GDP),Import (% GDP),...,Export,Import,Education Expenditure,Health Expenditure,Net Trade,GDP Per Capita,Population Density,GDP_in_billions,High_Population,Category
1886,Mongolia,MNG,2000-01-01,27.422531,66.857072,16.074770,53.996751,1.136896e+09,5.695384,67.889858,...,6.138870e+08,7.718372e+08,1.827534e+08,6.475059e+07,-1.579502e+08,463.853882,1.567002,1.136896,False,Low
1887,Mongolia,MNG,2001-01-01,22.968888,66.857072,17.633221,50.318341,1.267998e+09,5.054356,65.499986,...,6.380355e+08,8.305385e+08,2.235889e+08,6.408912e+07,-1.925029e+08,512.819470,1.580826,1.267998,False,Low
1888,Mongolia,MNG,2002-01-01,18.919125,66.857072,20.311510,50.726616,1.396556e+09,5.188564,67.790637,...,7.084255e+08,9.467340e+08,2.836616e+08,7.246118e+07,-2.383086e+08,559.827709,1.594901,1.396556,False,Low
1889,Mongolia,MNG,2003-01-01,18.439517,66.857072,17.633221,52.352050,1.595297e+09,4.102188,67.947344,...,8.351709e+08,1.083962e+09,2.813023e+08,6.544209e+07,-2.487913e+08,633.946560,1.608862,1.595297,False,Low
1890,Mongolia,MNG,2004-01-01,20.029777,66.857072,13.594450,60.787775,1.992067e+09,4.157186,70.541543,...,1.210933e+09,1.405235e+09,2.708105e+08,8.281391e+07,-1.943016e+08,784.912072,1.622605,1.992067,False,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2571,Singapore,SGP,2018-01-01,0.030137,85.843480,20.785370,177.350437,3.770000e+11,4.074188,147.846922,...,6.680000e+11,5.570000e+11,7.833374e+10,1.535437e+10,1.110000e+11,66836.538510,7788.226519,377.000000,False,High
2569,Singapore,SGP,2016-01-01,0.031582,85.441380,18.513870,164.672005,3.190000e+11,4.390976,138.464502,...,5.250000e+11,4.420000e+11,5.906480e+10,1.400853e+10,8.360979e+10,56895.643340,7798.724618,319.000000,False,High
2573,Singapore,SGP,2020-01-01,0.032890,85.589466,11.911990,181.988603,3.480000e+11,6.053882,150.785223,...,6.340000e+11,5.250000e+11,4.150044e+10,2.109125e+10,1.090000e+11,61274.006460,7810.174451,348.000000,False,High
2572,Singapore,SGP,2019-01-01,0.032194,86.198100,19.474260,175.594437,3.770000e+11,4.415237,146.109060,...,6.620000e+11,5.510000e+11,7.338631e+10,1.663827e+10,1.110000e+11,66070.470670,7856.155647,377.000000,False,High
2575,Singapore,SGP,2022-01-01,0.028110,85.589466,13.280472,186.552565,4.670000e+11,3.654665,150.309924,...,8.710000e+11,7.020000e+11,6.199172e+10,1.705956e+10,1.690000e+11,82807.649080,7952.802284,467.000000,False,High

In [80]:
# What is the average GDP per capita for each continent?
df_countries.groupby('Continent Name')['GDP Per Capita'].mean()

Continent Name
Africa            2136.664237
Asia             12387.644439
Europe           25957.628629
North America    13683.494341
Oceania          27699.105830
South America     6868.685988
Name: GDP Per Capita, dtype: float64

In [81]:
# How many records are there for each country in the dataset?
df_countries['Country Name'].value_counts()

Country Name
Cyprus           46
Azerbaijan       46
Armenia          46
Kazakhstan       46
Turkiye          46
                 ..
Uruguay          23
Uzbekistan       23
Venezuela, RB    23
Vietnam          23
Zambia           23
Name: count, Length: 131, dtype: int64

In [97]:
## What is the total education expenditure for each continent in the year 2010?
df_countries[df_countries['Year'].dt.year == 2010].groupby('Continent Name')['Education Expenditure'].sum()

Continent Name
Africa           2.596013e+11
Asia             2.788002e+12
Europe           2.300285e+12
North America    2.767749e+12
Oceania          1.891654e+11
South America    5.154706e+11
Name: Education Expenditure, dtype: float64

In [83]:
#Calculate the mean, minimum, and maximum of Health Expenditure (% GDP) grouped by continent name
df_countries.groupby('Continent Name')['Health Expenditure'].agg(['mean', 'min', 'max'])

                        mean           min           max
Continent Name
Africa          2.579311e+09  2.390940e+07  3.640094e+10
Asia            3.236603e+10  3.670146e+07  8.220000e+11
Europe          4.157514e+10  7.636357e+07  5.460000e+11
North America   2.808301e+11  2.675646e+08  3.970000e+12
Oceania         3.769151e+10  7.088322e+07  1.480000e+11
South America   2.246343e+10  3.423769e+08  2.060000e+11

In [98]:
# For each continent, calculate the average GDP Per Capita, but only for countries with Education Expenditure (% GDP) greater than 4%.
df_countries[df_countries['Education Expenditure'] > 4].groupby('Continent Name')['GDP Per Capita'].mean()

Continent Name
Africa            2136.664237
Asia             12387.644439
Europe           25957.628629
North America    13683.494341
Oceania          27699.105830
South America     6868.685988
Name: GDP Per Capita, dtype: float64

In [86]:
# Filter countries with a population over 50 million, create a column for GDP in billions, and show only the top 5 highest GDPs.How many unique countries are in the dataset?
df_countries[df_countries['Population'] > 50000000][['Country Name', 'GDP']].sort_values(by='GDP', ascending=False).head(20)

       Country Name           GDP
3058  United States  2.550000e+13
3057  United States  2.330000e+13
3055  United States  2.140000e+13
3056  United States  2.110000e+13
3054  United States  2.050000e+13
3053  United States  1.950000e+13
3052  United States  1.870000e+13
3051  United States  1.820000e+13
574           China  1.800000e+13
573           China  1.780000e+13
3050  United States  1.760000e+13
3049  United States  1.680000e+13
3048  United States  1.630000e+13
3047  United States  1.560000e+13
3046  United States  1.500000e+13
3044  United States  1.480000e+13
572           China  1.470000e+13
3043  United States  1.450000e+13
3045  United States  1.450000e+13
571           China  1.430000e+13

In [87]:
# Extract distinct combinations of Country Name and Continent Name.
df_countries[['Country Name', 'Continent Name']].drop_duplicates()

       Country Name Continent Name
0           Albania         Europe
23          Algeria         Africa
46           Angola         Africa
69          Armenia         Europe
70          Armenia           Asia
...             ...            ...
3059        Uruguay  South America
3082     Uzbekistan           Asia
3105  Venezuela, RB  South America
3128        Vietnam           Asia
3151         Zambia         Africa

[138 rows x 2 columns]

In [99]:
# How many distinct years of data are available?
df_countries['Year'].nunique()

23

In [103]:
#. Display the first 10 rows of countries sorted by Population Density for 2020.
# Filter for 2020
df_countries_2020 = df_countries[df_countries['Year'] == 2020]

# Sort by Population Density
sorted_df = df_countries_2020.sort_values(by='Population Density')

# Display first 10 rows
sorted_df.head(10)

,Country Name,Country Code,Year,Agriculture (% GDP),Ease of Doing Business,Education Expenditure (% GDP),Export (% GDP),GDP,Health Expenditure (% GDP),Import (% GDP),...,Population,Land,Continent Name,Export,Import,Education Expenditure,Health Expenditure,Net Trade,GDP Per Capita,Population Density
1860,Greenland,GRL,2020,17.446340,NaN,16.247248,35.951747,3.082909e+09,NaN,46.748179,...,56367,410450.000,North America,1.108360e+09,1.441204e+09,5.008879e+08,NaN,-3.328442e+08,54693.511410,0.137330
3102,Mongolia,MNG,2020,12.965656,66.857072,12.459902,57.660350,1.331298e+10,4.944511,55.178298,...,3294335,1564115.749,Asia,7.676312e+09,7.345877e+09,1.658784e+09,6.582619e+08,3.304351e+08,4041.174145,2.106196
3217,Namibia,NAM,2020,9.158178,60.786982,24.941380,33.677869,1.058375e+10,8.896257,43.247373,...,2489098,824290.000,Africa,3.564381e+09,4.577193e+09,2.639733e+09,9.415575e+08,-1.012812e+09,4252.041807,3.019687
273,Australia,AUS,2020,2.012103,80.657646,14.430000,24.008283,1.330000e+12,10.648995,20.225151,...,25655289,7741220.000,Oceania,3.190000e+11,2.680000e+11,1.910000e+11,1.410000e+11,5.020007e+10,51722.069000,3.314114
2113,Iceland,ISL,2020,4.639813,78.989322,15.280000,33.230155,2.155308e+10,9.557963,34.789069,...,366463,103000.000,Europe,7.162122e+09,7.498116e+09,3.293311e+09,2.060036e+09,-3.359941e+08,58813.796980,3.557893
4390,Suriname,SUR,2020,8.136028,47.225936,13.942350,52.090661,2.911807e+09,6.771878,45.428157,...,607065,163820.000,South America,1.516780e+09,1.322780e+09,4.059744e+08,1.971841e+08,1.939993e+08,4796.533314,3.705683
1998,Guyana,GUY,2020,16.851179,55.033552,14.571714,91.853279,5.471257e+09,5.508642,106.031384,...,797202,214970.000,South America,5.025529e+09,5.801249e+09,7.972559e+08,3.013919e+08,-7.757205e+08,6863.074346,3.708434
2688,Libya,LBY,2020,3.593862,32.603984,NaN,49.007230,4.680821e+10,3.672419,30.291333,...,6653942,1759540.000,Africa,2.293941e+10,1.417883e+10,NaN,1.718993e+09,8.760576e+09,7034.658365,3.781637
871,Canada,CAN,2020,1.823739,79.583546,10.000000,29.680845,1.650000e+12,12.939675,31.921078,...,38007166,9879750.000,North America,4.890000e+11,5.260000e+11,1.650000e+11,2.130000e+11,-3.691004e+10,43349.677860,3.846976
1561,Faroe Islands,FRO,2020,13.602593,NaN,14.357937,47.765759,3.248671e+09,NaN,49.143898,...,52415,12959.670,Europe,1.551752e+09,1.596524e+09,4.664421e+08,NaN,-4.477120e+07,61979.795440,4.044470

In [100]:
# Show the last 5 entries of GDP figures for Nigeria.
df_countries[df_countries['Country Name'] == 'Nigeria'].sort_values(by='GDP', ascending=False).tail(5)

,Country Name,Country Code,Year,Agriculture (% GDP),Ease of Doing Business,Education Expenditure (% GDP),Export (% GDP),GDP,Health Expenditure (% GDP),Import (% GDP),...,Export,Import,Education Expenditure,Health Expenditure,Net Trade,GDP Per Capita,Population Density,GDP_in_billions,High_Population,Category
2097,Nigeria,NGA,2004-01-01,27.230454,51.831352,7.03385,20.253803,1.360000e+11,4.633684,11.642067,...,2.749752e+10,1.580582e+10,9.549487e+09,6.290908e+09,1.169170e+10,992.745280,148.042097,136.000000,True,Low
2096,Nigeria,NGA,2003-01-01,33.827061,51.831352,7.03385,26.751381,1.050000e+11,5.053610,22.583584,...,2.801912e+10,2.365382e+10,7.367183e+09,5.293099e+09,4.365308e+09,786.802409,144.104919,105.000000,True,Low
2095,Nigeria,NGA,2002-01-01,36.965083,51.831352,7.03385,23.239719,9.505409e+10,2.490640,16.795449,...,2.209030e+10,1.596476e+10,6.685963e+09,2.367455e+09,6.125543e+09,733.538162,140.276287,95.054095,True,Low
2094,Nigeria,NGA,2001-01-01,24.475355,51.831352,7.03385,28.250958,7.403056e+10,3.189469,21.429542,...,2.091434e+10,1.586441e+10,5.207199e+09,2.361182e+09,5.049933e+09,586.833062,136.562865,74.030562,True,Low
2093,Nigeria,NGA,2000-01-01,21.357241,51.831352,7.03385,36.023266,6.944896e+10,3.197383,12.972334,...,2.501778e+10,9.009151e+09,4.884936e+09,2.220550e+09,1.600863e+10,565.305993,132.989796,69.448963,True,Low

In [90]:
#Slice to extract the 3rd to 7th rows from data on South American countries.
df_countries[df_countries['Continent Name'] == 'South America'].iloc[2:7]

,Country Name,Country Code,Year,Agriculture (% GDP),Ease of Doing Business,Education Expenditure (% GDP),Export (% GDP),GDP,Health Expenditure (% GDP),Import (% GDP),...,Export,Import,Education Expenditure,Health Expenditure,Net Trade,GDP Per Capita,Population Density,GDP_in_billions,High_Population,Category
278,Bolivia,BOL,2002-01-01,12.955119,50.835038,15.550057,21.634455,7.905485e+09,4.896451,27.715805,...,1.710309e+09,2.191069e+09,1.229307e+09,387088168.6,-4.807602e+08,888.198576,8.101898,7.905485,False,Low
279,Bolivia,BOL,2003-01-01,13.427237,50.835038,15.550057,25.600734,8.082400e+09,5.197096,26.367102,...,2.069154e+09,2.131095e+09,1.256818e+09,420050114.9,-6.194089e+07,892.355381,8.244623,8.082400,False,Low
280,Bolivia,BOL,2004-01-01,13.322384,50.835038,15.550057,31.138391,8.773452e+09,4.863157,26.325876,...,2.731912e+09,2.309688e+09,1.364277e+09,426666756.7,4.222237e+08,951.951623,8.389265,8.773452,False,Low
281,Bolivia,BOL,2005-01-01,11.792722,50.835038,15.550057,35.548143,9.549122e+09,5.074081,32.093798,...,3.394536e+09,3.064676e+09,1.484894e+09,484530241.1,3.298596e+08,1018.313662,8.535917,9.549122,False,Medium
282,Bolivia,BOL,2006-01-01,10.937548,50.835038,15.550057,41.771714,1.145185e+10,4.660875,32.766134,...,4.783632e+09,3.752327e+09,1.780769e+09,533756234.9,1.031305e+09,1200.068092,8.686361,11.451845,False,Medium